apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.fullname }}       # i27-eureka-devs
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas.default }} #1
  selector:
    matchLabels:
      name: {{ .Values.name }} # i27-eureka
  template:
    metadata:
      labels:
        name: {{ .Values.name }} # i27-eureka
    spec: 
      containers:
        - image: "{{ .Values.image.name }}:${{ .Values.image.tag }}" # registryname/reponame/appname:tagname
          name: {{ .Values.name }}
          

          # ${env.DOCKER_HUB}/${env.APPLICATION_NAME}:${GIT_COMMIT}