apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
spec: 
  selector:
    name: {{ .Values.name }}
  type: NodePort # ClusterIP, NodePort, LoadBalancer
  ports:
  - protocol: TCP
    port: 80 # This is the service port 
    targetPort: {{ .Values.targetport }}